
<!-- capturar un error y lanza un error genÃ©rico si el error capturado 
    no es el que se esperaba -->


<!DOCTYPE html>
<html>

<body>
    <script>
try {
    
    let objetoNoDefinido;
    console.log(objetoNoDefinido.propiedad);
    
} catch (error) {
    if (error.message !== 'Error esperado') {
        throw new Error('Se ha producido un error no esperado');
    }
}


    </script>
</body>

</html>