<!-- capturar un error y lanza un error genérico si el error capturado 
    no es el que se esperaba -->


<!DOCTYPE html>
<html>

<body>
    <script>
        try {
            let coche = {
                marca: 'Toyota',
                modelo: 'Corolla'
            };
            
            console.log(coche.color);

            throw new Error('Error inesperado');
        } catch (error) {
            if (error.message !== 'Error esperado') {
                throw new Error('Se ha producido un error no esperado');
            }
        }
        console.log('El programa continúa después del bloque try-catch');

    </script>
</body>

</html>